kind: PersistentVolume
apiVersion: v1
metadata:
  name: quickstart 
  labels:
    type: local
spec:
  storageClassName: standard 
  capacity:
    storage: 30Gi
  local:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master    
